updates:
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: .
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/golang.org/x/net/http2
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: examples/mnist
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: examples/pytorch_cuda_docker
  open-pull-requests-limit: 10
  package-ecosystem: docker
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - jinchihe
  directory: sdk/python
  open-pull-requests-limit: 10
  package-ecosystem: pip
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: .
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - dims
  - thockin
  - justinsb
  - tallclair
  - piosz
  - brancz
  - DirectXMan12
  - lavalamp
  directory: vendor/k8s.io/klog
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jayunit100
  - hoegaarden
  - andyxning
  - neolit123
  - pohly
  - yagonobre
  - vincepri
  - detiber
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/google.golang.org/appengine
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/json-iterator/go
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/hashicorp/golang-lru
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/go-openapi/jsonpointer
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/go-openapi/jsonreference
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/go-openapi/spec
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/go-openapi/swag
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/google/gofuzz
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/google/uuid
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/prometheus/procfs
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/konsorten/go-windows-terminal-sequences
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/github.com/sirupsen/logrus
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/golang.org/x/oauth2
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
- assignees:
  - andreyvelich
  - gaocegege
  - Jeffwan
  - johnugeorge
  directory: vendor/gopkg.in/yaml.v2
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  reviewers:
  - jinchihe
  schedule:
    interval: daily
version: 2
