language: go

go:
  - "1.10"

go_import_path: github.com/kubeflow/pytorch-operator

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - hack/verify-codegen.sh
  - go build -o pytorch-operator.v1beta2 github.com/kubeflow/pytorch-operator/cmd/pytorch-operator.v1beta2
  - go build -o pytorch-operator.v1 github.com/kubeflow/pytorch-operator/cmd/pytorch-operator.v1
  - gometalinter --config=linter_config.json ./pkg/...
  # We customize the build step because by default
  # Travis runs go test -v ./... which will include the vendor
  # directory.
  # With go 1.9 vendor will be automatically excluded.
  # For now though we just run all tests in pkg.
  # And we can not use ** because goveralls uses filepath.Match
  # to match ignore files and it does not support it.
  - goveralls -service=travis-ci -v -package ./pkg/... -ignore "pkg/client/*/*.go,pkg/client/*/*/*.go,pkg/client/*/*/*/*.go,pkg/client/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*.go,pkg/client/*/*/*/*/*/*/*.go,pkg/apis/pytorch/*/zz_generated.*.go"
