ignored = ["github.com/kubeflow/pytorch-operator"]

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/openapi-gen",

  # needed by generated clientsets, but not an explicit dep in client-gen itself
  "k8s.io/apimachinery/pkg/apimachinery/registered",
]

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.0.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "~v1.10.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/code-generator"
  # We can not use master since the generated package name is changed from tensorflow to kubeflow.
  revision = "961bc077103364eb5bda2c40e2b560d068c9a8c6"

[[override]]
  # To solve undefined: reference.ParseNormalizedNamed in Kubernetes.
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

[[override]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[override]]
  name = "github.com/juju/ratelimit"
  version = "1.0.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false
