apiVersion: "kubeflow.org/v1alpha1"
kind: "PyTorchJob"
metadata:
  name: "pytorch-smoke"
spec:
  backend: "tcp"
  masterPort: "23456"
  replicaSpecs:
    - replicas: 1
      replicaType: MASTER
      template:
        spec:
          containers:
          - image: gcr.io/refined-byte-127219/pytorch-smoke-test:1.0
            imagePullPolicy: Always
            name: pytorch
          restartPolicy: OnFailure
    - replicas: 3
      replicaType: WORKER
      template:
        spec:
          containers:
          - image: gcr.io/refined-byte-127219/pytorch-smoke-test:1.0
            imagePullPolicy: Always
            name: pytorch
          restartPolicy: OnFailure
