apiVersion: v1
kind: Pod
metadata:
  name: py-torchjob-worker
spec:
  containers:
  - image: pytorch/pytorch:latest
    imagePullPolicy: IfNotPresent
    name: worker
    volumeMounts:
      - name: training-result
        mountPath: /tmp/result
      - name: entrypoint
        mountPath: /tmp/entrypoint
    command: [/tmp/entrypoint/dist_train.py]
    env:
    - name: MASTER_PORT
      value: "23456"
    - name: MASTER_ADDR
      value: pytorch-master
    - name: WORLD_SIZE
      value: "3"
      # Rank 0 is the master
    - name: RANK
      value: "1"
  restartPolicy: OnFailure
  volumes:
    - name: training-result
      emptyDir: {}
    - name: entrypoint
      configMap:
        name: dist-train
        defaultMode: 0755
